import 'package:flutter/material.dart';
import 'package:flutterapp/ranimobileapp/generatedloginwidget8/generated/GeneratedLoginWidget9.dart';

/* Frame login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 45.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 270.0,
                height: 236.742431640625,
                child: GeneratedLoginWidget9(),
              )
            ]),
      ),
    ));
  }
}
