import 'package:flutter/material.dart';
import 'package:flutterapp/ranimobileapp/generatedsignupwidget5/generated/GeneratedLoginWidget19.dart';

/* Frame signup
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignupWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 47, 32, 29),
                ),
              ),
              Positioned(
                left: 45.0,
                top: 177.0,
                right: null,
                bottom: null,
                width: 270.0,
                height: 286.0,
                child: GeneratedLoginWidget19(),
              )
            ]),
      ),
    ));
  }
}
