import 'package:flutter/material.dart';
import 'package:flutterapp/ranimobileapp/generatedbestwidget9/generated/GeneratedHeaderWidget10.dart';
import 'package:flutterapp/ranimobileapp/generatedbestwidget9/generated/GeneratedBestvidWidget3.dart';
import 'package:flutterapp/ranimobileapp/generatedbestwidget9/generated/GeneratedDhsvcuhasnfkzcihgbredsaknbfherbdnkibcejhadbasknbfryhedn3.dart';
import 'package:flutterapp/ranimobileapp/generatedbestwidget9/generated/GeneratedKenapaharusbeliiniWidget3.dart';
import 'package:flutterapp/ranimobileapp/generatedbestwidget9/generated/GeneratedBestsellersWidget3.dart';
import 'package:flutterapp/ranimobileapp/generatedbestwidget9/generated/GeneratedFooterWidget10.dart';

/* Frame best
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBestWidget9 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 60.0,
                child: GeneratedHeaderWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedFooterWidget10(),
              ),
              Positioned(
                left: 20.0,
                top: 95.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 35.0,
                child: GeneratedBestsellersWidget3(),
              ),
              Positioned(
                left: 30.0,
                top: 162.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 200.0,
                child: GeneratedBestvidWidget3(),
              ),
              Positioned(
                left: 58.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 245.0,
                height: 33.0,
                child: GeneratedKenapaharusbeliiniWidget3(),
              ),
              Positioned(
                left: 51.0,
                top: 427.0,
                right: null,
                bottom: null,
                width: 263.0,
                height: 81.0,
                child:
                    GeneratedDhsvcuhasnfkzcihgbredsaknbfherbdnkibcejhadbasknbfryhedn3(),
              )
            ]),
      ),
    ));
  }
}
