import 'package:flutter/material.dart';
import 'package:flutterapp/ranimobileapp/generatedproductwidget1/generated/GeneratedProduct4Widget3.dart';
import 'package:flutterapp/ranimobileapp/generatedproductwidget1/generated/GeneratedHeaderWidget11.dart';
import 'package:flutterapp/ranimobileapp/generatedproductwidget1/generated/GeneratedProduct6Widget3.dart';
import 'package:flutterapp/ranimobileapp/generatedproductwidget1/generated/GeneratedProduct1Widget3.dart';
import 'package:flutterapp/ranimobileapp/generatedproductwidget1/generated/GeneratedProduct2Widget3.dart';
import 'package:flutterapp/ranimobileapp/generatedproductwidget1/generated/GeneratedProduct5Widget3.dart';
import 'package:flutterapp/ranimobileapp/generatedproductwidget1/generated/GeneratedProduct3Widget3.dart';
import 'package:flutterapp/ranimobileapp/generatedproductwidget1/generated/GeneratedFooterWidget11.dart';

/* Frame product
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProductWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 60.0,
                child: GeneratedHeaderWidget11(),
              ),
              Positioned(
                left: 0.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedFooterWidget11(),
              ),
              Positioned(
                left: 40.0,
                top: 82.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 153.0,
                child: GeneratedProduct1Widget3(),
              ),
              Positioned(
                left: 200.0,
                top: 82.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 153.0,
                child: GeneratedProduct2Widget3(),
              ),
              Positioned(
                left: 39.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 153.0,
                child: GeneratedProduct3Widget3(),
              ),
              Positioned(
                left: 199.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 153.0,
                child: GeneratedProduct4Widget3(),
              ),
              Positioned(
                left: 39.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 153.0,
                child: GeneratedProduct5Widget3(),
              ),
              Positioned(
                left: 199.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 153.0,
                child: GeneratedProduct6Widget3(),
              )
            ]),
      ),
    ));
  }
}
