import 'package:flutter/material.dart';
import 'package:flutterapp/ranimobileapp/generatedhomewidget9/generated/GeneratedFooterWidget9.dart';
import 'package:flutterapp/ranimobileapp/generatedhomewidget9/generated/GeneratedAnekaMacamKueKeringWidget2.dart';
import 'package:flutterapp/ranimobileapp/generatedhomewidget9/generated/GeneratedHeaderWidget9.dart';
import 'package:flutterapp/ranimobileapp/generatedhomewidget9/generated/GeneratedSearchbarWidget3.dart';
import 'package:flutterapp/ranimobileapp/generatedhomewidget9/generated/GeneratedRasaEnakHargaTerjangkauWidget2.dart';

/* Frame home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget9 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Image.asset(
                  "assets/images/d6f54a79df5a9b434dd30d66ef44ee8707af3af4.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 360.0,
                  height: 640.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 60.0,
                child: GeneratedHeaderWidget9(),
              ),
              Positioned(
                left: 55.0,
                top: 129.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 30.0,
                child: GeneratedSearchbarWidget3(),
              ),
              Positioned(
                left: 30.0,
                top: 282.0,
                right: null,
                bottom: null,
                width: 204.0,
                height: 21.0,
                child: GeneratedRasaEnakHargaTerjangkauWidget2(),
              ),
              Positioned(
                left: 30.0,
                top: 239.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 33.0,
                child: GeneratedAnekaMacamKueKeringWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedFooterWidget9(),
              )
            ]),
      ),
    ));
  }
}
