import 'package:flutter/material.dart';
import 'package:flutterapp/ranimobileapp/generatedbestwidget1/generated/GeneratedFooterWidget1.dart';
import 'package:flutterapp/ranimobileapp/generatedbestwidget1/generated/GeneratedKenapaharusbeliiniWidget.dart';
import 'package:flutterapp/ranimobileapp/generatedbestwidget1/generated/GeneratedBestsellersWidget.dart';
import 'package:flutterapp/ranimobileapp/generatedbestwidget1/generated/GeneratedBestvidWidget.dart';
import 'package:flutterapp/ranimobileapp/generatedbestwidget1/generated/GeneratedHeaderWidget1.dart';
import 'package:flutterapp/ranimobileapp/generatedbestwidget1/generated/GeneratedDhsvcuhasnfkzcihgbredsaknbfherbdnkibcejhadbasknbfryhedn.dart';

/* Frame best
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBestWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 120.0,
                              child: GeneratedHeaderWidget1(),
                            ),
                            Positioned(
                              left: 80.0,
                              top: 200.0,
                              right: null,
                              bottom: null,
                              width: 1280.0,
                              height: 100.0,
                              child: GeneratedBestsellersWidget(),
                            ),
                            Positioned(
                              left: 80.0,
                              top: 400.0,
                              right: null,
                              bottom: null,
                              width: 700.0,
                              height: 400.0,
                              child: GeneratedBestvidWidget(),
                            ),
                            Positioned(
                              left: 842.0,
                              top: 400.0,
                              right: null,
                              bottom: null,
                              width: 488.0,
                              height: 65.0,
                              child: GeneratedKenapaharusbeliiniWidget(),
                            ),
                            Positioned(
                              left: 842.0,
                              top: 474.0,
                              right: null,
                              bottom: null,
                              width: 435.0,
                              height: 129.0,
                              child:
                                  GeneratedDhsvcuhasnfkzcihgbredsaknbfherbdnkibcejhadbasknbfryhedn(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 936.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 88.0,
                              child: GeneratedFooterWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
