import 'package:flutter/material.dart';
import 'package:flutterapp/ranimobileapp/generatedloginpagewidget/generated/GeneratedLoginWidget.dart';

/* Frame login-page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginpageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 47, 32, 29),
                              ),
                            ),
                            Positioned(
                              left: 370.0,
                              top: 262.0,
                              right: null,
                              bottom: null,
                              width: 700.0,
                              height: 500.0,
                              child: GeneratedLoginWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
