import 'package:flutter/material.dart';
import 'package:flutterapp/ranimobileapp/generatedhomewidget/generated/GeneratedHeaderWidget.dart';
import 'package:flutterapp/ranimobileapp/generatedhomewidget/generated/GeneratedRasaEnakHargaTerjangkauWidget.dart';
import 'package:flutterapp/ranimobileapp/generatedhomewidget/generated/GeneratedFooterWidget.dart';
import 'package:flutterapp/ranimobileapp/generatedhomewidget/generated/GeneratedSearchbarWidget.dart';
import 'package:flutterapp/ranimobileapp/generatedhomewidget/generated/GeneratedAnekaMacamKueKeringWidget.dart';

/* Frame home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Image.asset(
                                "assets/images/d6f54a79df5a9b434dd30d66ef44ee8707af3af4.png",
                                color: null,
                                fit: BoxFit.contain,
                                width: 1440.0,
                                height: 1024.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 120.0,
                              child: GeneratedHeaderWidget(),
                            ),
                            Positioned(
                              left: 80.0,
                              top: 246.0,
                              right: null,
                              bottom: null,
                              width: 640.0,
                              height: 60.0,
                              child: GeneratedSearchbarWidget(),
                            ),
                            Positioned(
                              left: 101.0,
                              top: 473.0,
                              right: null,
                              bottom: null,
                              width: 541.0,
                              height: 52.0,
                              child: GeneratedRasaEnakHargaTerjangkauWidget(),
                            ),
                            Positioned(
                              left: 101.0,
                              top: 375.0,
                              right: null,
                              bottom: null,
                              width: 733.0,
                              height: 100.0,
                              child: GeneratedAnekaMacamKueKeringWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 936.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 88.0,
                              child: GeneratedFooterWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
