import 'package:flutter/material.dart';
import 'package:flutterapp/ranimobileapp/generatedproductwidget/generated/GeneratedProduct1Widget2.dart';
import 'package:flutterapp/ranimobileapp/generatedproductwidget/generated/GeneratedProduct2Widget2.dart';
import 'package:flutterapp/ranimobileapp/generatedproductwidget/generated/GeneratedProduct6Widget2.dart';
import 'package:flutterapp/ranimobileapp/generatedproductwidget/generated/GeneratedProduct5Widget2.dart';
import 'package:flutterapp/ranimobileapp/generatedproductwidget/generated/GeneratedProduct3Widget2.dart';
import 'package:flutterapp/ranimobileapp/generatedproductwidget/generated/GeneratedProduct4Widget2.dart';
import 'package:flutterapp/ranimobileapp/generatedproductwidget/generated/GeneratedHeaderWidget8.dart';
import 'package:flutterapp/ranimobileapp/generatedproductwidget/generated/GeneratedFooterWidget8.dart';

/* Frame product
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProductWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 40.0,
                top: 73.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 153.0,
                child: GeneratedProduct1Widget2(),
              ),
              Positioned(
                left: 40.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 153.0,
                child: GeneratedProduct3Widget2(),
              ),
              Positioned(
                left: 40.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 153.0,
                child: GeneratedProduct5Widget2(),
              ),
              Positioned(
                left: 200.0,
                top: 73.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 153.0,
                child: GeneratedProduct2Widget2(),
              ),
              Positioned(
                left: 200.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 153.0,
                child: GeneratedProduct4Widget2(),
              ),
              Positioned(
                left: 200.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 153.0,
                child: GeneratedProduct6Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedFooterWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 60.0,
                child: GeneratedHeaderWidget8(),
              )
            ]),
      ),
    ));
  }
}
