import 'package:flutter/material.dart';
import 'package:flutterapp/ranimobileapp/generatedbestwidget8/generated/GeneratedBestvidWidget2.dart';
import 'package:flutterapp/ranimobileapp/generatedbestwidget8/generated/GeneratedDhsvcuhasnfkzcihgbredsaknbfherbdnkibcejhadbasknbfryhedn2.dart';
import 'package:flutterapp/ranimobileapp/generatedbestwidget8/generated/GeneratedFooterWidget7.dart';
import 'package:flutterapp/ranimobileapp/generatedbestwidget8/generated/GeneratedKenapaharusbeliiniWidget2.dart';
import 'package:flutterapp/ranimobileapp/generatedbestwidget8/generated/GeneratedHeaderWidget7.dart';
import 'package:flutterapp/ranimobileapp/generatedbestwidget8/generated/GeneratedBestsellersWidget2.dart';

/* Frame best
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBestWidget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 95.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 35.0,
                child: GeneratedBestsellersWidget2(),
              ),
              Positioned(
                left: 30.0,
                top: 162.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 200.0,
                child: GeneratedBestvidWidget2(),
              ),
              Positioned(
                left: 58.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 245.0,
                height: 33.0,
                child: GeneratedKenapaharusbeliiniWidget2(),
              ),
              Positioned(
                left: 51.0,
                top: 427.0,
                right: null,
                bottom: null,
                width: 263.0,
                height: 81.0,
                child:
                    GeneratedDhsvcuhasnfkzcihgbredsaknbfherbdnkibcejhadbasknbfryhedn2(),
              ),
              Positioned(
                left: 0.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedFooterWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 60.0,
                child: GeneratedHeaderWidget7(),
              )
            ]),
      ),
    ));
  }
}
